
-- ex1
DROP DATABASE IF EXISTS  Fresher_Training_Management;
CREATE DATABASE  IF NOT EXISTS  Fresher_Training_Management;
USE Fresher_Training_Management;
CREATE TABLE Trainee (
    TraineeID INT AUTO_INCREMENT PRIMARY KEY,
    Full_Name VARCHAR(50) NOT NULL,
    Birth_Date DATE NOT NULL,
    Gender ENUM('male', 'female', 'unknown'),
    ET_IQ TINYINT UNSIGNED  ,
    ET_Gmath TINYINT UNSIGNED ,
    ET_English SMALLINT UNSIGNED,
    Training_Class VARCHAR(50) ,
    Evaluation_Notes VARCHAR(50)
    
);

ALTER TABLE Trainee 
ADD COLUMN VTI_Account VARCHAR(50) NOT NULL UNIQUE;

-- ex2
DROP DATABASE IF EXISTS  ex2;
CREATE DATABASE IF NOT EXISTS  ex2;

CREATE TABLE bang (
    ID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(20) NOT NULL,
    `Code` CHARACTER(5) NOT NULL,
    ModifiedDate DATETIME 
);

-- ex3
DROP DATABASE IF EXISTS  ex3;
CREATE DATABASE IF NOT EXISTS  ex3;

CREATE TABLE bang3 (
    ID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(20) NOT NULL,
    BirthDate DATE,
    Gender ENUM('0', '1', 'NULL') NOT NULL,
    IsDeletedFlag ENUM('0', '1') NOT NULL
);


